version: "2"
networks:
  mq-net:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    volumes:
      - /home/kxw/datas/rabbitmq_data:/var/lib/rabbitmq
    #environment:
    #  - MYSQL_ROOT_PASSWORD=000000
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mq-net
