version: "2"
services:
  influxdb:
    image: influxdb 
    network_mode: "bridge"
    volumes:
      - /home/kxw/dev/influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
  chronograf:
    image: quay.io/influxdb/chronograf:1.5.0.0
    network_mode: "bridge"
    ports:
      - "8888:8888"
    #command:
    #  - influxdb-url=http://localhost:8086

  neo4j: 
    image: neo4j 
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /home/kxw/dev/neo4j_data:/data
  cassandra:
    image: cassandra
    network_mode: "bridge"
    ports:
      - "9160:9160"
      - "9042:9042"
        #hbase:
        #image: harisekhon/hbase
        #network_mode: "bridge"
    #ports:
    #  - "9160:9160"
    #volumes:
    #  - /home/kxw/dev/hbase_data:/hbase-data
  opentsdb:
    image: petergrace/opentsdb-docker 
    network_mode: "bridge"
    ports:
      - "60030:60030"
      - "4242:4242"
    volumes:
      - /home/kxw/dev/opentsdb_data:/data/hbase
  graphite:
    image: graphiteapp/graphite-statsd
    network_mode: "bridge"
    ports:
      - "4243:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
        #prometheus:
        #image: prom/prometheus
        #network_mode: "bridge"
        #ports:
        #- "9090:9090"
