version: "2"
services:
  influxdb:
    image: influxdb 
    network_mode: "host"
    volumes:
      - /home/kxw/dev/influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
  neo4j: 
    image: neo4j 
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /home/kxw/dev/neo4j_data:/data
   
