version: "2"
networks:
  oms-net:
    driver: bridge
services:
  portainer:
    image: portainer/portainer
    #network_mode: "bridge"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oms-net
  nginx:
    image: nginx:1.15
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - gateway
    links:
      - gateway:oms.gateway-server
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  mysql:
    image: mysql:5.7.25
    volumes:
      - /home/kxw/datas/mysql_data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    ports:
      - "3307:3306"
    networks:
      - oms-net

  zookeeper:
    image: zookeeper:3.4
    #network_mode: "bridge"
    ports:
      - "3181:2181"
    networks:
      - oms-net
  elasticsearch:
    image: elasticsearch:5.6
    #network_mode: "bridge"
    networks:
      - oms-net
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/kxw/datas/es_data:/usr/share/elasticsearch/data
      #environment:
      #- discovery.type=single-node
      #- cluster.name=elasticsearch
      #- transport.host=0.0.0.0
      #- http.host=0.0.0.0
      #- discovery.zen.minimum_master_nodes=1
  redis:
    image: redis:4.0
    #network_mode: "bridge"
    ports:
      - "6379:6379"
    networks:
      - oms-net
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    #network_mode: "bridge"
    networks:
      - oms-net
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.88.2.107
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
  influxdb:
    image: influxdb:1.5.2
    #network_mode: "bridge"
    volumes:
      - /home/kxw/datas/influxdb_data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    networks:
      - oms-net
  logstash-online:
    image: docker.elastic.co/logstash/logstash:5.6.8
    #network_mode: "bridge"
    volumes:
      - ./logstash/logstash-online/galaxy-online.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash-online/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash-online/es-template/galaxy-online-template.json:/usr/share/logstash/es-template/galaxy-online-template.json
      #environment:
      #- PATH_CONFIG=/usr/share/logstash/pipeline
      #- XPACK_MONITORING_ENABLED=false
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - "10515:10515"
    networks:
      - oms-net
  logstash-batch:
    image: docker.elastic.co/logstash/logstash:5.6.8
    #network_mode: "bridge"
    volumes:
      - ./logstash/logstash-batch/galaxy-batch.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash-batch/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash-batch/es-template/galaxy-batch-template.json:/usr/share/logstash/es-template/galaxy-batch-template.json
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - "10516:10516"
    networks:
      - oms-net
    #chronograf:
    #image: quay.io/influxdb/chronograf:1.5.0.0
    #network_mode: "bridge"
    #ports:
    #  - "8888:8888"
  #Disable eureka, as if eureka server version is uncompatible with eureka client, client will report discovery heartbeat error."
  #eureka:
  #  image: springcloud/eureka
  #  network_mode: "bridge"
  #  ports:
  #    - "8761:8761"
  eureka:
    image: kswapd/oms-eureka:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    ports:
      - "9527:9527"
  gateway:
    image: kswapd/oms-gateway:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
    ports:
      - "8081:8081"
    links:
      - eureka:oms.service-discovery-eureka-server
  auth:
    image: kswapd/oms-auth:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
    ports:
      - "8085:8085"
    links:
      - eureka:oms.service-discovery-eureka-server
      - mysql:oms.storage-mysql-server
      - redis:oms.cache-redis-server
  alarm:
    image: kswapd/oms-alarm:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
      - mysql
    ports:
      - "8092:8092"
    links:
      - eureka:oms.service-discovery-eureka-server
      - mysql:oms.storage-mysql-server
  log-server:
    image: kswapd/oms-log-server:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
      - mysql
      - elasticsearch
    ports:
      - "8093:8093"
    links:
      - eureka:oms.service-discovery-eureka-server
      - elasticsearch:oms.storage-elasticsearch-server
      - gateway:oms.gateway-server
  monitor-server:
    image: kswapd/oms-monitor-server:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - alarm
      - eureka
      - mysql
      - gateway
      - kafka
      - influxdb

    ports:
      - "8014:8014"
    links:
      - eureka:oms.service-discovery-eureka-server
      - gateway:oms.gateway-server
      - kafka:oms.mq-kafka-server
      - influxdb:oms.storage-influxdb-server
      - alarm:oms.alarm-server
  deploy-server:
    image: kswapd/oms-deploy:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
      - mysql
      - gateway
      - kafka
    ports:
      - "8012:8012"
    links:
      - eureka:oms.service-discovery-eureka-server
      - gateway:oms.gateway-server
      - mysql:oms.storage-mysql-server
      - kafka:oms.mq-kafka-server
  opeation-server:
    image: kswapd/oms-operation:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
      - mysql
      - gateway
      - kafka
    ports:
      - "9679:9679"
    links:
      - eureka:oms.service-discovery-eureka-server
      - gateway:oms.gateway-server
      - mysql:oms.storage-mysql-server
      - kafka:oms.mq-kafka-server
  zipkin-server:
    image: kswapd/oms-zipkin-server:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - eureka
      - mysql
      - gateway
      - elasticsearch
    ports:
      - "9411:9411"
    #links:
    #  - eureka:oms.service-discovery-eureka-server
    links:
      - eureka:oms.service-discovery-eureka-server
      - gateway:oms.gateway-server
      - mysql:oms.storage-mysql-server
      - elasticsearch:oms.storage-elasticsearch-server
  zipkin-server-dependency:
    image: kswapd/oms-zipkin-server-dependency:1.0
    #network_mode: "bridge"
    networks:
      - oms-net
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:oms.storage-elasticsearch-server