version: "2"
#todo influxdb&logstash&filebeat
services:
  nginx:
    image: nginx:1.15 
    network_mode: "bridge"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  zookeeper:
    image: zookeeper:3.4
    network_mode: "bridge"
    ports:
      - "3181:2181"
  elasticsearch:
    image: elasticsearch:5.6
    #image: elasticsearch:2.4.4
    network_mode: "bridge"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /home/kxw/dev/docker-devops/oms/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #environment:
      #- discovery.type=single-node
      #- cluster.name=elasticsearch
      #- transport.host=0.0.0.0
      #- http.host=0.0.0.0
      #- discovery.zen.minimum_master_nodes=1
  redis:
    image: redis:4.0
    network_mode: "bridge"
    ports:
      - "6379:6379"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    network_mode: "bridge"
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.88.2.105
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
  influxdb:
    image: influxdb:1.5.2 
    network_mode: "bridge"
    volumes:
      - /home/kxw/datas/influxdb_data:/var/lib/influxdb
      - /home/kxw/dev/docker-devops/oms/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
  logstash-online:
    image: docker.elastic.co/logstash/logstash:5.6.8
    network_mode: "bridge"
    volumes:
      - ./logstash/logstash-online/galaxy-online.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash-online/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash-online/es-template/galaxy-online-template.json:/usr/share/logstash/es-template/galaxy-online-template.json
    #environment:
      #- PATH_CONFIG=/usr/share/logstash/pipeline 
      #- XPACK_MONITORING_ENABLED=false
    links:
      - elasticsearch:es
    ports:
      - "10515:10515"
  logstash-batch:
    image: docker.elastic.co/logstash/logstash:5.6.8
    network_mode: "bridge"
    volumes:
      - ./logstash/logstash-batch/galaxy-batch.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash-batch/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash-batch/es-template/galaxy-batch-template.json:/usr/share/logstash/es-template/galaxy-batch-template.json
    links:
      - elasticsearch:es
    ports:
      - "10516:10516"
  #chronograf:
    #image: quay.io/influxdb/chronograf:1.5.0.0
    #network_mode: "bridge"
    #ports:
    #  - "8888:8888"
  #Disable eureka, as if eureka server version is uncompatible with eureka client, client will report discovery heartbeat error."  
  #eureka:
  #  image: springcloud/eureka
  #  network_mode: "bridge"
  #  ports:
  #    - "8761:8761"
