version: "2"
networks:
  oms-net:
    driver: bridge
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oms-net
  mysql:
    image: mysql:5.7.25
    volumes:
      - /home/kxw/datas/mysql_data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    ports:
      - "3306:3306"
    networks:
      - oms-net
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    networks:
      - oms-net
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    networks:
      - oms-net
  eureka:
    image: kswapd/oms-eureka:1.0
    networks:
      - oms-net
    ports:
      - "9527:9527"
  gateway:
    image: kswapd/oms-gateway:1.0
    networks:
      - oms-net
    depends_on:
      - eureka
    ports:
      - "8081:8081"
    links:
      - eureka:oms.service-discovery-eureka-server
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.instance.ipAddress=10.88.2.115
  nginx:
    image: nginx:1.15
    networks:
      - oms-net
    depends_on:
      - gateway
    links:
      - gateway:oms.gateway-server
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.instance.ipAddress=10.88.2.115

