version: "2"
services:
  nginx:
    image: nginx:1.15 
    network_mode: "bridge"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
