version: "2"
services:
  zookeeper:
    image: zookeeper 
    network_mode: "bridge"
    ports:
      - "2181:2181"
#  mysql:
#    image: mysql:5.7
#    network_mode: "bridge"
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=aaaaaa
#    volumes:
#      - /home/kxw/dev/mysql_data:/var/lib/mysql
