version: "2"
services:
  influxdb:
    image: influxdb:1.5.2 
    network_mode: "bridge"
    volumes:
      - /home/kxw/datas/influxdb_data:/var/lib/influxdb
      - /home/kxw/dev/docker-devops/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
  chronograf:
    image: quay.io/influxdb/chronograf:1.5.0.0
    network_mode: "bridge"
    ports:
      - "8888:8888"
